## IBM Quantum Challenge Fall 2021

# Challenge 3c Hint

### 3つのラベル確率から3クラス分類予測への変換
チャレンジ3cでは，3つのラベル確率から3クラス分類予測を作成する必要があります。ここでは，そのヒントを示しています。以下は，5データに対して実装すべき変換の例です。

**入力**: 3つのラベル確率
- ラベル0: [0.1, 0.5, 0.2, 0.9, 0.4]
- ラベル2: [0.3, 0.1, 0.1, 0.3, 0.6]
- ラベル3: [0.6, 0.2, 0.4, 0.1, 0.3]

**出力**: 3クラス分類予測
- 予測: [3, 0, 3, 0, 2]

この変換規則は，各データに対してラベル確率の最も高いラベルを予測とするものになっています。例えば最初のデータを見てみると，ラベル0, 2, 3の確率がそれぞれ0.1, 0.3, 0.6となっており，ラベル3の確率が最も高くなっているので，予測はラベル3とされています。

こうした変換規則は，様々なアプローチによって実装することが可能です。チャレンジ3のノートブックでは，np.whereを用いたアプローチを紹介しました。このヒントでは，np.argmaxを用いたアプローチを追加で紹介します。ここではチャレンジ3のノートブックと同様に，2つのラベルに対してのみデモンストレーションをしているので，提出にあたってはこれを3ラベル用に拡張する必要があります。

まず，上記のサンプルデータを定義します。

In [5]:
import numpy as np

pred_0 = [0.1, 0.5, 0.2, 0.9, 0.4]
pred_2 = [0.3, 0.1, 0.1, 0.3, 0.6]

array([[0.1, 0.5, 0.2, 0.9, 0.4],
       [0.3, 0.1, 0.1, 0.3, 0.6]])

次に，データを一まとめにします。

In [7]:
pred_02 = np.vstack([pred_0, pred_2])
pred_02

array([[0.1, 0.5, 0.2, 0.9, 0.4],
       [0.3, 0.1, 0.1, 0.3, 0.6]])

そして，np.argmaxを適用します。これによって，どのラベル確率がより高いか分かります。今回の場合は，結果"0"はラベル0の確率がより高く，結果"1"はラベル2の確率がより高いことを表しています。

In [15]:
argmax_02 = np.argmax(pred_02, axis=0)
argmax_02

array([1, 0, 0, 0, 1])

最後にそれぞれの値を対応するラベルに変換することで，"pred_test"を得ます。

In [16]:
pred_test_02 = np.where(argmax_02==0, 0, 2)
pred_test_02

array([2, 0, 0, 0, 2])

これを3ラベル用に拡張することで，提出用のpred_testを作成することができます。

## Additional information

**Created by:** Shota Nakasuji

**Version:** 0.1.0