## IBM Quantum Challenge Fall 2021

# Challenge 3c Hint

### How to convert three label probabilities into 3-class prediction
In Challenge 3c, you need to create a final 3-class classification prediction from three label probabilities. Here is a hint for that part. The following is an example of what you should implement for 5 samples.

**Input**: three label probalibities
- label 0: [0.1, 0.5, 0.2, 0.9, 0.4]
- label 2: [0.3, 0.1, 0.1, 0.3, 0.6]
- label 3: [0.6, 0.2, 0.4, 0.1, 0.3]

**Output**: 3-class classification prediction
- prediction: [3, 0, 3, 0, 2]

The conversion rule is to use the label with the highest label probability as the prediction for each data. For example, looking at the first data, the probalities of label 0, 2, 3 are 0.1, 0.3, 0.6 respectively, where the probability of label 3 is the highest, therefore the prediction is chosen to be label 3.

Such conversion rules can be implemented by a great variety of approaches. The Challenge 3 notebook gives a hint of an approach using np.where. In this hint, an additional approach using np.argmax is presented. Here, as in the Challenge 3 notebook, it is demonstrated for just two labels, so you will need to extend it for three labels for submission.

First, define the example data shown above.

In [1]:
import numpy as np

pred_0 = [0.1, 0.5, 0.2, 0.9, 0.4]
pred_2 = [0.3, 0.1, 0.1, 0.3, 0.6]

Next, stack the data.

In [2]:
pred_02 = np.vstack([pred_0, pred_2])
pred_02

array([[0.1, 0.5, 0.2, 0.9, 0.4],
       [0.3, 0.1, 0.1, 0.3, 0.6]])

Then, apply np.argmax. This allows us to get which label probability is higher. In this case,  the result "0" means label 0 probability is higher while the result "1" means label 2 probability is higher.

In [3]:
argmax_02 = np.argmax(pred_02, axis=0)
argmax_02

array([1, 0, 0, 0, 1])

Finally, convert each value to its corresponding label, and you have "pred_test".

In [4]:
pred_test_02 = np.where(argmax_02==0, 0, 2)
pred_test_02

array([2, 0, 0, 0, 2])

By extending this approach for 3 labels, you can get pred_test for submission.

## Additional information

**Created by:** Shota Nakasuji

**Version:** 0.1.0